name: macOS System Extension & XPC Service

on:
  push:
    paths:
      - 'service/firewall/interception/macos/**'
      - 'macos-app-placeholder/**'
      - 'Earthfile'
    branches:
      - master
      - develop
  pull_request:
    paths:
      - 'service/firewall/interception/macos/**'
      - 'macos-app-placeholder/**'
      - 'Earthfile'
    branches:
      - master
      - develop

jobs:
  build_macos_native:
    name: Build macOS Network Extension and XPC Service
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Earthly
      uses: earthly/actions-setup@v1
      with:
        version: v0.8.0

    # Add this step to install Docker
    - name: Install Docker
      run: |
        brew install --cask docker
        open -g -a Docker
        while ! docker system info > /dev/null 2>&1; do sleep 1; done

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Run macOS Native Builds via Earthly
      run: |
        earthly --ci --remote-cache=ghcr.io/safing/build-cache --push +kext-build-macos
        earthly --ci --remote-cache=ghcr.io/safing/build-cache --push +xpc-service-macos
